services:
  tou-service:
    build: ./tou-service
    container_name: tou-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgis/postgis:15-3.3
    container_name: tou-chargers-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - tou_chargers_db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - tou-service
    restart: unless-stopped

volumes:
  tou_chargers_db_data:
